name: .NET CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build application
        run: dotnet build --no-restore

      - name: Run tests
        run: dotnet test --no-restore --verbosity normal

      - name: Publish application
        run: dotnet publish -c Release -o ./publish --no-restore

      - name: Upload application artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyApp
          path: ./publish

           # =========================
  # CD
  # =========================
  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: MyApp
          path: ./deploy

      - name: Deploy to IIS
        shell: powershell -ExecutionPolicy Bypass -File "{0}"
        run: |
          Write-Host "Starting IIS deployment..."

          Import-Module WebAdministration

          # Stop website if running
          $site = Get-Website -Name "MyApp"

          if ($site.State -eq "Started") {
              Write-Host "Stopping website..."
              Stop-Website -Name "MyApp"
          }
          else {
              Write-Host "Website is already stopped."
          }

          # Stop application pool if running
          $pool = Get-WebAppPoolState -Name "DefaultAppPool"

          if ($pool.Value -eq "Started") {
              Write-Host "Stopping application pool..."
              Stop-WebAppPool -Name "DefaultAppPool"
          }
          else {
              Write-Host "Application pool is already stopped."
          }

          # Give IIS time to release files
          Write-Host "Waiting for IIS..."
          Start-Sleep -Seconds 5

          # Remove old files
          Write-Host "Removing old application files..."
          Remove-Item "C:\inetpub\wwwroot\MyApp\*" -Recurse -Force

          # Copy new artifact
          Write-Host "Copying new application files..."
          Copy-Item ".\deploy\*" `
            "C:\inetpub\wwwroot\MyApp" `
            -Recurse -Force

          # Start application pool
          Write-Host "Starting application pool....."
          Start-WebAppPool -Name "DefaultAppPool"

          # Start website
          Write-Host "Starting website..."
          Start-Website -Name "MyApp"

          Write-Host "Deployment completed successfullyyyyy!"