name: .NET CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build application
        run: dotnet build --no-restore

      - name: Run tests
        run: dotnet test --no-restore --verbosity normal

      - name: Publish application
        run: dotnet publish -c Release -o ./publish --no-restore

      - name: Upload application artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyApp
          path: ./publish

           # =========================
  # CD
  # =========================
  deploy:
    needs: build
    runs-on: self-hosted

    steps:

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: MyApp
          path: ./deploy

      - name: Deploy to IIS
        shell: powershell
        run: |
          Write-Host "Starting IIS deployment..."

          Import-Module WebAdministration

          Stop-Website -Name "MyApp"

          Remove-Item "C:\inetpub\wwwroot\MyApp\*" -Recurse -Force
          Copy-Item ".\deploy\*" 
            "C:\inetpub\wwwroot\MyApp" 
            -Recurse -Force

          Start-Website -Name "MyApp"

          Write-Host "IIS deployment completed."